# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_item',
            old_name='question',
            new_name='list_task',
        ),
    ]
