# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20171019_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_item',
            name='completed',
            field=models.IntegerField(default=0),
        ),
    ]
